function detFisop = detFisop_4node_func(in1,in2,in3,in4,in5)
%detFisop_4node_func
%    detFisop = detFisop_4node_func(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    24-Feb-2025 15:40:04

xe11 = in2(1,:);
xe12 = in2(2,:);
xe21 = in3(1,:);
xe22 = in3(2,:);
xe31 = in4(1,:);
xe32 = in4(2,:);
xe41 = in5(1,:);
xe42 = in5(2,:);
xi1 = in1(1,:);
xi2 = in1(2,:);
t2 = (xe12.*xe21)./8.0;
t3 = (xe11.*xe42)./8.0;
t4 = (xe21.*xe32)./8.0;
t5 = (xe31.*xe42)./8.0;
t6 = xe22.*xe31.*(-1.0./8.0);
t7 = xe32.*xe41.*(-1.0./8.0);
detFisop = -t2-t3+t4+t5+t6+t7+t2.*xi2+t3.*xi1+t4.*xi1+t5.*xi2+t6.*xi1+t7.*xi2+(xe11.*xe22)./8.0+(xe12.*xe41)./8.0-(xe11.*xe22.*xi2)./8.0-(xe11.*xe32.*xi1)./8.0+(xe12.*xe31.*xi1)./8.0+(xe11.*xe32.*xi2)./8.0-(xe12.*xe31.*xi2)./8.0-(xe12.*xe41.*xi1)./8.0-(xe21.*xe42.*xi1)./8.0+(xe22.*xe41.*xi1)./8.0-(xe21.*xe42.*xi2)./8.0+(xe22.*xe41.*xi2)./8.0;
end
